cc_test(
    name = "strong_units_tests",
    srcs = glob(["StrongUnit_test.cpp"]),
    deps = [
        "//src/lib:StrongUnit",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "strong_complex_units_tests",
    srcs = glob(["StrongCUnit_test.cpp"]),
    deps = [
        "//src/lib:StrongUnit",
        "@googletest//:gtest_main",
    ],
)
