# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "example1",
    srcs = ["example1.cpp"],
    deps = ["//src/lib:StrongUnit"],
)

cc_binary(
    name = "example2",
    srcs = ["example2.cpp"],
    deps = ["//src/lib:StrongUnit"],
)

cc_binary(
    name = "example3",
    srcs = ["example3.cpp"],
    deps = ["//src/lib:StrongUnit"],
)

cc_binary(
    name = "example4",
    srcs = ["example4.cpp"],
    deps = ["//src/lib:StrongUnit"],
)

cc_binary(
    name = "example5",
    srcs = ["example5.cpp"],
    deps = ["//src/lib:StrongUnit"],
)

cc_binary(
    name = "usecase1",
    srcs = ["usecase1.cpp"],
    deps = ["//src/lib:StrongUnit"],
)
